### ISSUE TITLE
Rim Disorders and Babies (1.4 Core/Biotech)

### ISSUE THREAD

**Issue by MrXarous** [emipa606/RFRimDisorders#3]
User Trooper50000 reported an error with Rim Disorders applying PTSD to babies while playing. I isolated the error to just Core/DLC and Rim Disorders.

Started dev quickstart:
Spawned in baby pawn.
Had a crib.
Had baby food.
Had care.

Approx 3 days in-game the letter PTSD came upon mouse over stated Baby had developed PTSD due to being downed. I don't know if this interaction is specifically due to how vanilla coded babies and their interactions from being placed into a crib. Or the 0% movement stat. Or if the C# patch for AgeMatters can be also applicable to vanilla age. Either way I hope this helps and reach me on Discord for any other information about said issue.

**Comment by MrXarous** [comment]
Also note that the same user contacted me again through Discord with the issue of paralytic abasia pawn suffering from PTSD just because they were suffering from paralytic abasia. IDK if you want to tweak the chances of that triggering, but I figured it's how the game treats downed pawn and how the mod interacts with that condition.

**Comment by emipa606** [comment]
Now ignores children from biotech and pawns with paralytic abasia
8b19ca2
